"""add file_path to case_files

Revision ID: 246bc42ce503
Revises: 48ba61975411
Create Date: 2025-12-30 08:57:44.517221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '246bc42ce503'
down_revision: Union[str, Sequence[str], None] = '48ba61975411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_files', sa.Column('file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_files', 'file_path')
    # ### end Alembic commands ###
