"""add file_size to case_files

Revision ID: 43d2ad07dc61
Revises: e2dbeff7d831
Create Date: 2025-12-30 09:08:45.298372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d2ad07dc61'
down_revision: Union[str, Sequence[str], None] = 'e2dbeff7d831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_files', sa.Column('file_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_files', 'file_size')
    # ### end Alembic commands ###
