"""use jsonb for case_metadata.parties

Revision ID: 4703a5ca5b67
Revises: a8b2aa268a86
Create Date: 2026-01-07 12:59:21.609567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4703a5ca5b67'
down_revision: Union[str, Sequence[str], None] = 'a8b2aa268a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_metadata_id'), table_name='case_metadata')
    op.drop_table('case_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_metadata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parties', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('court_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('filing_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('judge', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attorney', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('next_court_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('strong_evidence', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('approaching_deadline', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('case_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('case_metadata_case_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('case_metadata_pkey')),
    sa.UniqueConstraint('case_id', name=op.f('case_metadata_case_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_case_metadata_id'), 'case_metadata', ['id'], unique=False)
    # ### end Alembic commands ###
