"""add content_type

Revision ID: e2dbeff7d831
Revises: 246bc42ce503
Create Date: 2025-12-30 09:03:15.516248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2dbeff7d831'
down_revision: Union[str, Sequence[str], None] = '246bc42ce503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_files', sa.Column('content_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_files', 'content_type')
    # ### end Alembic commands ###
